#!/bin/bash
# update-fancontrol-config.sh
# Dynamically updates /etc/fancontrol with current hwmon indices before service start.

set -e

# --- Configuration ---
# Drivers to match in /sys/class/hwmon/hwmon*/name
TEMP_SENSOR_DRIVER="coretemp"
FAN_CTRL_DRIVER="nct6779"

# Fan to Sensor Mappings (Arrays must be the same length)
# Format: PWM_PINS[0] is controlled by TEMP_INPUTS[0] and monitored by FAN_INPUTS[0]
PWM_PINS=("pwm2")
TEMP_INPUTS=("temp1_input")
FAN_INPUTS=("fan2_input")

# Default Fan Curve Settings (Applied to all fans)
MINTEMP=40
MAXTEMP=60
MINSTART=14
MINSTOP=12
MINPWM=12
MAXPWM=255
# ---------------------

# Find current hwmon indices (e.g., hwmon1, hwmon2)
CORE_HWMON=$(grep -l "$TEMP_SENSOR_DRIVER" /sys/class/hwmon/hwmon*/name | head -n 1 | cut -d/ -f5)
NCT_HWMON=$(grep -l "$FAN_CTRL_DRIVER" /sys/class/hwmon/hwmon*/name | head -n 1 | cut -d/ -f5)

if [ -z "$CORE_HWMON" ] || [ -z "$NCT_HWMON" ]; then
    echo "Error: Could not find required hwmon devices ($TEMP_SENSOR_DRIVER, $FAN_CTRL_DRIVER)." >&2
    exit 1
fi

# Resolve physical device paths for DEVPATH
CORE_DEVPATH=$(readlink -f /sys/class/hwmon/"$CORE_HWMON"/device | sed 's|^/sys/||')
NCT_DEVPATH=$(readlink -f /sys/class/hwmon/"$NCT_HWMON"/device | sed 's|^/sys/||')

# Generate the /etc/fancontrol config file
{
  echo "# Generated by update-fancontrol-config.sh"
  echo "INTERVAL=10"
  echo "DEVPATH=$CORE_HWMON=$CORE_DEVPATH $NCT_HWMON=$NCT_DEVPATH"
  echo "DEVNAME=$CORE_HWMON=$TEMP_SENSOR_DRIVER $NCT_HWMON=$FAN_CTRL_DRIVER"

  for i in "${!PWM_PINS[@]}"; do
    PWM="${PWM_PINS[$i]}"
    TEMP="${TEMP_INPUTS[$i]}"
    FAN="${FAN_INPUTS[$i]}"
    
    echo "FCTEMPS=$NCT_HWMON/$PWM=$CORE_HWMON/$TEMP"
    echo "FCFANS=$NCT_HWMON/$PWM=$NCT_HWMON/$FAN"
    echo "MINTEMP=$NCT_HWMON/$PWM=$MINTEMP"
    echo "MAXTEMP=$NCT_HWMON/$PWM=$MAXTEMP"
    echo "MINSTART=$NCT_HWMON/$PWM=$MINSTART"
    echo "MINSTOP=$NCT_HWMON/$PWM=$MINSTOP"
    echo "MINPWM=$NCT_HWMON/$PWM=$MINPWM"
    echo "MAXPWM=$NCT_HWMON/$PWM=$MAXPWM"
  done
} > /etc/fancontrol
